### ISSUE TITLE
Suggestions should not work within strings

### ISSUE THREAD

**Issue by InternetUnexplorer** [viluon/LuaExtended#1]
![](http://i.imgur.com/70e8njL.png)

**Comment by viluon** [comment]
Argh, looked into this a bit, but completions can only be disabled via a regex. Given that the whole line has to be matched (not only, like, the part left to the cursor) and ST adds the second quote for strings automagically, there's literally no way to fix this. This could be maybe handled by python, I'll see what I can do.

**Comment by InternetUnexplorer** [comment]
Don't worry about it too much, it's not that much of a problem :smile:

**Comment by viluon** [comment]
Turns out [scope selectors](https://stackoverflow.com/questions/37406338/sublime-text-modifying-tmtheme-file/37407588#37407588) can be used to fix this. Thanks for the report!
