### ISSUE TITLE
Indentation Problems

### ISSUE THREAD

**Issue by devidasjadhav** [viluon/LuaExtended#15]
I have used re-indent on previously written lua file it did failed to indent properly elseif blocks and braces at times
So I used solution mentioned in [this](http://blog.lotech.org/2013/04/fixing-lua-indenting-in-sublime-text.html)
it seems issue is in "Indent.tmPreferences" file I fixed it and working fine now.

**Comment by viluon** [comment]
Thank you very much for the bug report, @devidasjadhav, especially then for the linked solution. I will look into this issue as soon as possible.

**Comment by devidasjadhav** [comment]
I forgot to thank you for time saving solution made thanks a lot for this project.
Also for showing concern to looking into it.

**Comment by InternetUnexplorer** [comment]
Thanks for the bug report! I was wondering if you could include steps to reproduce the issue, as the indentation seems to be working fine for me:
![](http://i.imgur.com/VHrYkch.gif)

Could you perhaps include an example of where it is not working?

**Comment by viluon** [comment]
@InternetUnexplorer @devidasjadhav said (s)he used (probably) the Reindent Lines command. It seems that any text after an indent-changing keyword breaks the settings:
![](http://i.imgur.com/JxpCe4J.png)
![](http://i.imgur.com/86mMle2.png)

This could be a really simple fix, I'll mess with the regex right now.

**Comment by viluon** [comment]
Huh, this could be a problem with ST3 itself: [regular expressions 101](https://regex101.com/) seem to match the `increaseIndentPattern` correctly
![](http://i.imgur.com/UEDPJUF.png)
Likewise, the `decreaseIndentPattern` is matched as it should be
![](http://i.imgur.com/zLCuMDt.png)
The relevant patterns can be found [here](https://github.com/viluon/LuaExtended/blob/66fcf93f01183d5a0e2f10d86bc5de64c9eadf11/Indent.tmPreferences).
Test string:
```Lua
if a then
b()
elseif c then
d()
else -- damn you, ST3
e()
if x then -- woop
do
foo()
end -- of everything
y()
elseif z then -- tricky comment
_()
--[[ the ]] end -- is near
end
```
