### ISSUE TITLE
Problems on Ubuntu 16.04

### ISSUE THREAD

**Issue by DebugLyu** [viluon/LuaExtended#16]
i install this package, but it not work.
does this plug can used on ubuntu?

**Comment by InternetUnexplorer** [comment]
Thank you for your feedback.
Can you please be a bit more specific about what is not working?
And could you also include details about how you installed the package (from package control?), etc.
Thanks!

**Comment by viluon** [comment]
LuaExtended is a cross-platform package, but requires Sublime Text build 3092+. [Package Control](http://packagecontrol.io) ensures a stress-free installation.

We cannot work with the information given. You will have to share more details about the current state of affairs in your system, so to speak, as @InternetUnexplorer said.

**Comment by viluon** [comment]
Without more information, this issue is unsolvable. Closing as invalid for lack of reporter's feedback.
