### ISSUE TITLE
Compatibility with Sublime Text 4 / Project still being maintained?

### ISSUE THREAD

**Issue by alexdyas** [viluon/LuaExtended#20]
Hi,

I can't get this to work with Sublime Text version 4. I've installed it as per the instructions **Package Control: Install Packages**. It seems to install ok, but I don't see any evidence that it is running, no completions as per the examples in the documentation.

No other Lua related packages installed.

Am I doing something wrong?

Cheers,

Alexander

**Comment by viluon** [comment]
Hi @alexdyas,

unfortunately, I've abandoned LuaExtended long ago. The Sublime Text approach to language extensions was always fundamentally limited in the analysis it could easily do. [Language servers](https://en.wikipedia.org/wiki/Language_Server_Protocol) replaced "smart" language extensions in the wild, for the better of the ecosystem. I recommend finding an ST 4 -compatible language server for your use case or switching to an editor that supports language servers out-of-the-box. The [Lua LS](https://github.com/LuaLS/lua-language-server) is quite popular.

Thanks for your interest in LuaExtended!

Happy hacking,
@viluon

**Comment by alexdyas** [comment]
Hi @viluon,

Thanks a lot for taking the time to reply. No worries. Eventually I swapped to vim for my Lua development where I found what I needed.

All the best for your other projects.

Alexander.

**Comment by alexdyas** [comment]
No longer being maintained.
