### ISSUE TITLE
Concatenated error highlighting

### ISSUE THREAD

**Issue by hbomb79** [viluon/LuaExtended#7]
If the string inside of the `error` call is broken up via concatenation, the highlighting does not carry through:

![](http://puu.sh/sYgm7/85cd2ca95a.png)

Also, if the error call doesn't have parentheses around the string, it is not colored at all:
![](http://puu.sh/sYgn1/96bebbbfd3.png)

**Comment by viluon** [comment]
I know about this one, should fix - thanks for the report!
